# Generated by Django 5.1.4 on 2024-12-29 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام برچسب (فارسی)')),
                ('name_en', models.CharField(max_length=255, verbose_name='نام برچسب (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'برچب',
                'verbose_name_plural': 'برچسب\u200cهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام دسته (فارسی)')),
                ('name_en', models.CharField(max_length=255, verbose_name='نام دسته (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('poster', models.ImageField(blank=True, default='images/shop/category/default.png', null=True, upload_to='images/shop/category/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, jpeg, webp'])], verbose_name='پوستر')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین عکس')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop.productcategory', verbose_name='شناسه والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام محصول (فارسی)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام محصول (انگلیسی)')),
                ('page_title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات مختصر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('sales', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('in_stock', models.IntegerField(verbose_name='موجودیت')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='امتیاز')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('poster', models.ImageField(blank=True, default='images/shop/product/default.png', null=True, upload_to='images/shop/product/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, jpeg, webp'])], verbose_name='پوستر')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین عکس')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_shop.productcategory', verbose_name='دسته بندی محصولات')),
                ('tag', models.ManyToManyField(related_name='product_tags', to='app_shop.producttag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'لیست محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/shop/product/gallery/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, jpeg, webp'])], verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product', verbose_name='شناسه محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ترتیب نمایش')),
                ('property', models.CharField(max_length=255, verbose_name='ویژگی')),
                ('content', models.CharField(max_length=255, verbose_name='محتوا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product', verbose_name='شناسه محصول')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
            },
        ),
    ]
