# Generated by Django 5.1.4 on 2025-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_province_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام صفحه')),
                ('model', models.CharField(choices=[('main', 'اصلی'), ('landing', 'لندینگ'), ('article', 'مقالات'), ('product', 'محصولات')], max_length=255, verbose_name='مدل')),
                ('generated', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], max_length=255, verbose_name='روش تولید')),
                ('parent', models.IntegerField(default=0, verbose_name='شناسه والد')),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='url')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'صفحه فرود',
                'verbose_name_plural': 'صفحات فرود',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین عکس'),
        ),
    ]
