# Generated by Django 5.1.4 on 2024-12-29 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام برچسب (فارسی)')),
                ('name_en', models.CharField(max_length=255, verbose_name='نام برچسب (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'برچب',
                'verbose_name_plural': 'برچسب\u200cهای مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='نام دسته (فارسی)')),
                ('name_en', models.CharField(max_length=255, verbose_name='نام دسته (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('poster', models.ImageField(blank=True, default='images/blog/category/default.png', null=True, upload_to='images/blog/category/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, jpeg, webp'])], verbose_name='پوستر')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین عکس')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.articlecategory', verbose_name='شناسه والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('page_title', models.CharField(max_length=255, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('intro', models.TextField(verbose_name='مقدمه')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('poster', models.ImageField(blank=True, default='images/blog/article/default.png', null=True, upload_to='images/blog/article/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, jpeg, webp'])], verbose_name='پوستر')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/blog/article/', verbose_name='ویدیو')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین عکس')),
                ('published', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
                ('preview', models.BooleanField(default=False, verbose_name='نمایش / عدم نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_blog.articlecategory', verbose_name='دسته بندی مقالات\u200c')),
                ('tag', models.ManyToManyField(to='app_blog.articletag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
