# Generated by Django 5.1.4 on 2024-12-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('rejected', 'رد شده'), ('approved', 'تایید شده')], default='pending', max_length=225, verbose_name='وضعیت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.article', verbose_name='شناسه مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
