# Generated by Django 5.1.4 on 2025-02-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_core', '0003_page_province_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کاتالوگ')),
                ('model', models.CharField(choices=[('article', 'مقاله'), ('product', 'محصول')], max_length=255, verbose_name='مدل')),
                ('type', models.CharField(choices=[('list', 'لیست'), ('grid', 'گرید')], max_length=255, verbose_name='نوع کاتالوگ')),
                ('generated', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], max_length=255, verbose_name='روش تولید')),
                ('see_all_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک موارد بیشتر')),
                ('max_items', models.IntegerField(default=0, verbose_name='حداکثر تعداد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.page', verbose_name='شناسه صفحه')),
            ],
            options={
                'verbose_name': 'کاتالوگ',
                'verbose_name_plural': 'لیست کاتالوگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='شناسه آیتم')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugin_catalog.catalog', verbose_name='شناسه مجموعه')),
            ],
            options={
                'verbose_name': 'اجزا کاتالوگ',
                'verbose_name_plural': 'لیست اجزا کاتالوگ',
            },
        ),
    ]
