# Generated by Django 5.1.4 on 2024-12-29 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_province_slug'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='mobile', max_length=255, verbose_name='نوع')),
                ('dest', models.CharField(max_length=255, verbose_name='ایمیل / موبایل')),
                ('token', models.CharField(max_length=255, verbose_name='کد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires', models.DateTimeField(verbose_name='زمان انقضا')),
            ],
            options={
                'verbose_name': 'کد فعالسازی',
                'verbose_name_plural': 'کدهای فعالسازی',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/account/user/default.png', null=True, upload_to='images/account/user/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='عکس پروفایل'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, verbose_name='محله')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='longitude')),
                ('zip', models.CharField(max_length=50, verbose_name='کد پستی')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.city', verbose_name='شناسه شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.province', verbose_name='شناسه استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
    ]
